### ISSUE TITLE
Non-modal dialogs/popups are hard to see due to missing border/margin

### ISSUE THREAD

**Issue by t0r0X** [lzxgh/OneDarkDarker#1]
Hello,

many thanks for this IntelliJ theme, it is the one I like most. Nevertheless, I have a small issue: non-modal popups/dialogs have no border, and it is hard for me to see where their margin/border is, and sometimes to locate them on a large screen. I wish this could be improved.

Here some examples:
* One Dark Darker modal dialog: 
![intellij-dialog-border-01-modal-one-dark-darker](https://user-images.githubusercontent.com/9170345/236439538-1f1c5022-eb68-48e5-b9cd-971250fabbd8.png)
* One Dark Darker non-modal dialog (Find in files): 
![intellij-dialog-border-02-non-modal-one-dark-darker](https://user-images.githubusercontent.com/9170345/236439673-d907a944-15e1-454e-9f59-6d15c8ce39f1.png)
* Darcula non-modal (Surround with): 
![intellij-dialog-border-03-non-modal-darcula](https://user-images.githubusercontent.com/9170345/236439775-dcc4532b-d2d4-4cfb-aefb-79cfaa42de18.png)
* One Dark Darker non-modal (Surround with):  
![intellij-dialog-border-03-one-dark-darker](https://user-images.githubusercontent.com/9170345/236439888-c7f06499-040d-4ff9-b377-b84c74f7ddbe.png)

I hope it's possible to implement a tweak to either improve the visibility of border/margin color, or to make the popup background lighter.

PS
The screenshots are better cases, where the popups are over some text/code, but on a large screen with large resolution this goes under in the black surroundings, at least on my screen.

**Comment by lzxgh** [comment]
Accepted, Popup/Dialog border colors were added in version 1.3.2.
![image](https://github.com/lzxgh/OneDarkDarker/assets/14898773/ddff26a3-fe50-434e-9cf8-963f497b505f)
<img width="722" alt="image" src="https://github.com/lzxgh/OneDarkDarker/assets/14898773/6ba1fc21-a8e4-479c-9a97-a740ec631116">
