### ISSUE TITLE
Webstorm 2023.2.1 code is in default / light mode 

### ISSUE THREAD

**Issue by Destaq** [lzxgh/OneDarkDarker#2]
After updating to the latest version of the theme and Webstorm, I have found that the 'screen' holding the code seems to be in the default light mode.

<img width="1440" alt="Screenshot 2023-08-28 at 1 11 41 PM" src="https://github.com/lzxgh/OneDarkDarker/assets/61620873/0c07d125-fbd1-45fc-84f0-335ed0e30653">

This unfortunately makes OneDarkDarker unusable in Webstorm for now. If you could take a look at this, it would be much appreciated... yours is the best theme on the market!

**Comment by lzxgh** [comment]
This issue seem cause by Settings Sync, https://youtrack.jetbrains.com/issue/IDEA-325237/Dont-apply-an-incompatible-color-scheme-during-settings-sync

Manually set Color Scheme to One Dark Darker can solve this issue, steps show in the bellow screenshots:

<img width="930" alt="image" src="https://github.com/lzxgh/OneDarkDarker/assets/14898773/6d8454cc-e35c-491a-a259-0e4df067b3d3">

**Comment by Destaq** [comment]
That did the trick, thank you!
