### ISSUE TITLE
Misplaced accent colors

### ISSUE THREAD

**Issue by Apxdono** [lzxgh/OneDarkDarker#3]
There's a difference between accent colors  of tabs and `target` folders (Excluded folders) between different languages. If one compares Java and Rust target folders in Idea and Rover, those are highlighted differently:

Excluded folder:
Idea:
![image](https://github.com/lzxgh/OneDarkDarker/assets/1544058/dcb8ffd8-b037-4a29-92fa-258bfd5f9a76)

RustRover:
![image](https://github.com/lzxgh/OneDarkDarker/assets/1544058/6d84420a-d095-42f0-a653-b5f0143ae3e0)

Tabs:
Idea: 
![image](https://github.com/lzxgh/OneDarkDarker/assets/1544058/8245f29f-c2c2-4f4e-aad5-2f6a6f1bbbc8)

RustRover:
![image](https://github.com/lzxgh/OneDarkDarker/assets/1544058/09c8e3c7-b3d9-4c00-804b-249ab421c38b)

I tried to identify why this discrepancy occurs but no luck so far (apart from obvious being the EAP for RR).

## IntelliJ IDEA 2023.3.2 (Community Edition)
Build #IC-233.13135.103, built on December 22, 2023
Runtime version: 17.0.10+7 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Linux 6.7.1-zen1-1-zen
GC: G1 Young Generation, G1 Old Generation
Memory: 4002M
Cores: 16
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.obelisk.onedarkdarker (1.3.8)
  com.intellij.marketplace (233.13135.127)
  Docker (233.13135.108)
  InnerBuilder Continued (1.0.5)
  com.jetbrains.packagesearch.intellij-plugin (233.11799.196)
  YourKit Java Profiler 2022.3-b103 Integration (2022.3.103.0)
  izhangzhihao.rainbow.brackets (2024.1.0-233)
  com.mallowigi (94.1.0)
Kotlin: 233.13135.103-IJ
Current Desktop: KDE

## RustRover 2023.3 EAP
Build #RR-233.13135.127, built on January 23, 2024
Licensed to RustRover EAP User
Expiration date: March 23, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.7.1-zen1-1-zen
GC: G1 Young Generation, G1 Old Generation
Memory: 4002M
Cores: 16
Registry:
  ide.balloon.shadow.size=0
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  transferSettings.vscode.onlyCargoToml=true
Non-Bundled Plugins:
  org.editorconfig.editorconfigjetbrains (233.13135.68)
  com.obelisk.onedarkdarker (1.3.8)
  com.intellij.swagger (233.13135.14)
  com.mallowigi (94.1.0)
Current Desktop: KDE

**Comment by lzxgh** [comment]
Can't reproduce this issue on both Ubuntu 22.04 and Windows 11, it may be caused by other plugins or IDE settings.

You can try cleanly reinstalling RustRover, don't import previous settings and plugins, then one by one reinstall plugins.
